[phases.setup]
nixPkgs = ["python311", "gcc", "bash"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["chmod +x railway-start.sh"]

[start]
cmd = "./railway-start.sh"
